/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_storyteller_f_uiscale_JDPILibrary */

#ifndef _Included_com_storyteller_f_uiscale_JDPILibrary
#define _Included_com_storyteller_f_uiscale_JDPILibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_storyteller_f_uiscale_JDPILibrary
 * Method:    getDPI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_storyteller_1f_uiscale_JDPILibrary_getDPI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
